sonar.projectKey=SAIKO9X_microservice-hms-project
sonar.organization=saiko-projects
sonar.projectName=HMS Backend - Hospital Management System
# ignorar arquivos SQL de migração/seed do Flyway
sonar.exclusions=**/src/main/resources/db/migration/**/*.sql