server:
  port: ${SERVER_PORT:8083}
  shutdown: graceful # Aguarda requests terminarem antes de matar o processo

services:
  profile:
    base-url: "${PROFILE_URI:http://localhost:8082}"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s # tempo máximo para shutdown gracioso
  config:
    import: "optional:classpath:common-application.yml"
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_appointment_db}
    username: ${DB_USER:mysql_appointment_user}
    password: ${DB_PASSWORD:mysql_appointment_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    clean-disabled: false

application:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
  rabbitmq:
    exchange: internal.exchange
    prescription-issued-routing-key: prescription.issued
    appointment-status-routing-key: appointment.status.changed
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      profileService:
        baseConfig: default
      userService:
        baseConfig: default
  retry:
    instances:
      profileService:
        maxAttempts: 3
        waitDuration: 1s
      userService:
        maxAttempts: 3
        waitDuration: 1s

app:
  security:
    encryption-key: ${ENCRYPTION_KEY:ThisIsAFixedKeyForEncryption32Ch}